version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5434:5432"  # Changed host port to 5434

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/foodtales
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydatabase  # Keep this as 5432
