# Generated by Django 5.1.1 on 2024-09-11 16:07

import datetime
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.IntegerField(choices=[(1, '1st (3 points)'), (2, '2nd (2 points)'), (3, '3rd (1 point)')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
